# Python 3

Welcome to Python 3!

In this notebook we will:

1. Import required modules and dataset
2. Aggregate large amounts of data
3. Merge multiple data sources into a DataFrame
4. Create spreadsheet-style pivot tables as a DataFrame




%pip install numpy pandas sklearn

- DataFrame basics

In [4]:
import numpy as np
import pandas as pd

# Case Study: Rating courses (1: Creation)
Imagine that we are interested in gathering data about student performance for each course. We will need to store specific information about the course:
- Course code: to identify the course
- Semester
- Professor
- Difficulty (subjective to students)
- Student Grade
One way to store this data is to use a list of dictionaries. We use dictionaries since we need to store different information for each of the instances. Each key within the dictionary is a column and each dictionary is a row. So we follow two steps to create a pandas dataframe:
1. Make the list of dictionaries and populate it with data
2. pass the list to pd.DataFrame()

In [20]:
list_of_dicts = [
    {'code': 'ECN101','semester': 'F2022', 'prof': 'A', 'diff': 4.5, 'grade': 88},
    {'code': 'MTH202','semester': 'F2022', 'prof': 'B', 'diff': 5, 'grade': 45},
    {'code': 'ECN101','semester': 'W2022', 'prof': 'C', 'diff': 2.5, 'grade': 98},
    {'code': 'ECN101','semester': 'W2022', 'prof': 'B', 'diff': 3.5, 'grade': 90},
    {'code': 'MTH202','semester': 'F2022', 'prof': 'A', 'diff': 4.2, 'grade': 89},
    {'code': 'ECN101','semester': 'F2022', 'prof': 'A', 'diff': 3.2, 'grade': 18},
    {'code': 'MTH202','semester': 'W2022', 'prof': 'C', 'diff': 1.5, 'grade': 76},
    {'code': 'ECN101','semester': 'F2022', 'prof': 'C', 'diff': 5.0, 'grade': 46},
    {'code': 'MTH202','semester': 'F2022', 'prof': 'A', 'diff': 2.7, 'grade': 76},
    {'code': 'MTH202','semester': 'W2022', 'prof': 'C', 'diff': 1.5, 'grade': 82},
    {'code': 'ECN101','semester': 'F2022', 'prof': 'B', 'diff': 4.0, 'grade': 90},
    {'code': 'MTH202','semester': 'W2022', 'prof': 'B', 'diff': 1.5, 'grade': 65},
]

ratings = pd.DataFrame(list_of_dicts)

In [21]:
ratings

code semester prof  diff  grade
0   ECN101    F2022    A   4.5     88
1   MTH202    F2022    B   5.0     45
2   ECN101    W2022    C   2.5     98
3   ECN101    W2022    B   3.5     90
4   MTH202    F2022    A   4.2     89
5   ECN101    F2022    A   3.2     18
6   MTH202    W2022    C   1.5     76
7   ECN101    F2022    C   5.0     46
8   MTH202    F2022    A   2.7     76
9   MTH202    W2022    C   1.5     82
10  ECN101    F2022    B   4.0     90
11  MTH202    W2022    B   1.5     65

# Case Study: Rating courses (2: Wrangling)

Pandas offers a diverse set of features to work with data. We list a few of them and showcase each of them

- describe: This will describe the dataset features such as average, standard deviation, count, and etc.
    - min
    - max
    - mean
    - std
    - qunatile
- shape: returns (# of rows, # of columns)
- .T: transpose, rotates the dataframe

In [11]:
ratings.describe()

diff      grade
count  12.0  12.000000
mean    4.5  71.916667
std     0.0  24.066039
min     4.5  18.000000
25%     4.5  60.250000
50%     4.5  79.000000
75%     4.5  89.250000
max     4.5  98.000000

# Case Study: Rating courses (2: Analysis)

groupby(): combines 3 steps all in one function:
1. Split a DataFrame
2. Apply a function
3. Combine the results

Examples: 
1. What is the average grade that students got for each professor? (Hint: use .mean())
2. What is the average grade that students got for a given semester? (Hint: use .mean())
3. What is the average grade that students got for each professor with respect to each course?
4. What is the average grade that students got for each professor with respect to each course and semester?

# Groupby exercises:
1. What is the average difficulty that students got for each professor with respect to each course?
2. What is the average difficulty that students got for each professor with respect to each course and semester?
3. Use describe by exercises 1 and 2 and note the differences?
4. What is the grade and difficulty average for with respect to semester, prof, and course?

# Case Study: Rating courses (2: Analysis) (cont.)

What would students with high marks label the course difficulty? 

## pivot_tables
- values: these are the values that are going to be used as metric
- index: Is one of the factors in sub setting the dataset
- columns: Similar to index but it is horizontal

Examples:
1. What is the difficulty average for different grades and professors?
2. What is the grade average for different difficulty and professors?

# Programming exercise: Generating random data
By looking at the pivot table we realize to fully use the functionality of pivot tables we will neeed more instances. But since we don't have access to actual real world data, we can generate data randomly using the following structures:
- We can limit the number of semesters, courses, and etc.
- Define a possible list of values
- Choose randomly from the possible values
- Populate rows

In [58]:
# Note: You do not need understand every last bit of code here; just understand the overall logic behind it
import random

possible_courses = ['ECN101', 'MTH202', 'BTM178', 'HST675']
possible_sems = ['F2022', 'W2022','F2021', 'W2021','F2020', 'W2020']
possible_profs = ['A', 'B', 'C', 'D', 'E', 'F', 'G']

NUM_INSTANCES = 1000

l = []

for i in range(NUM_INSTANCES):
    instance = {}
    instance['prof'] = random.choice(possible_profs)
    instance['semester'] = random.choice(possible_sems)
    instance['code'] = random.choice(possible_courses)

    instance['grade'] = random.randint(70,100)
    instance['diff'] = random.randint(0,100) / 20

    l.append(instance)

gen_data = pd.DataFrame(l)

# Pivot tables exercise

1. What is the difficulty average for different grades and professors on the generated data?
2. What is the max difficulty for different semesters and professors on the generated data?
2. What is the average grade for different semesters and professors on the generated data?

# Case Study: Rating courses (2: Analysis) (cont.)

- value_counts(): Number of repition for a given value within a column
- hbar: horizontal barchart

Examples:
1. What are the repetition of unique values within code column?
2. What are the repetition of unique values within code and prof column?
3. Use *.plot.barh()* after the value_counts() in examples 1 and 2 to make a horizontal bar chart.

# Case Study: Rating courses (3: Manipulation)

How would we convert numerical grades to grade codes?
- There is a reached which corresponds to a letter 90-100 -> A+
- Apply function: Go through every instance and check its range

Putting the values within ranges will make it easier to analyze our data. What if we did the same for difficulty levels and made the pivot tables again?

In [78]:
def grade_convert(num):
    if num > 90:
        return 'A+'
    elif num > 80:
        return "A"
    elif num > 70:
        return "B"
    else:
        return "C"

gen_data['letter'] = gen_data.grade.apply(grade_convert)
gen_data.pivot_table(values='diff', index="prof", columns = 'letter', aggfunc='max')

letter     A   A+     B     C
prof                         
A       5.00  5.0  4.85  4.10
B       4.95  5.0  4.90  3.85
C       5.00  5.0  4.80  4.15
D       5.00  4.9  4.80  3.80
E       5.00  5.0  4.80  4.80
F       5.00  5.0  5.00  2.25
G       5.00  5.0  4.95  4.40

In [89]:
def diff_convert(num):
    if num > 3.5:
        return 'Hard'
    elif num > 2:
        return "Medium"
    else:
        return "Easy"

gen_data['level'] = gen_data['diff'].apply(diff_convert)
gen_data.pivot_table(values='grade', index="prof", columns = 'level', aggfunc='mean')

level       Easy       Hard     Medium
prof                                  
A      84.578947  85.400000  85.318182
B      83.526316  83.244444  83.975000
C      85.758065  83.159091  85.944444
D      86.758065  85.916667  83.388889
E      85.032258  85.428571  85.051282
F      85.541667  85.100000  84.829268
G      86.631579  84.132075  85.200000

# Exercise: apply function
1. Change the grade_convert function: add B+ and A-.
2. Change the difficulty level: hard when bigger than 4 and medium if bigger than 2.5.
3. Get the number of occurrences for unique values within the letter column and plot a horizontal bar chart.

# Regression

- Load data
- Run a regression model
- Evaluate performance 

## EDA

1. Are there any missing values within the data?
2. What is the correlation of target column with feature columns?
3. Split the data into train and test.

In [81]:
from sklearn import datasets

raw = datasets.load_diabetes()

df = pd.DataFrame(raw['data'], columns=raw['feature_names'])
df['target'] = raw['target']

## Run regression

1. Regression: y = w * x + b
    - Linear, Ridge, and Lasso
    - Check the different weights 
    - score returns coefficient of determination
2. Decision tree

In [113]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

reg = LinearRegression().fit(X_train, y_train)
lasso = Lasso().fit(X_train, y_train)
ridge = Ridge().fit(X_train, y_train)

print(reg.score(X_test,y_test), lasso.score(X_test,y_test), ridge.score(X_test,y_test))

0.5103942572821248 0.36246898582743314 0.44451113757354543


In [116]:
reg.coef_, lasso.coef_, ridge.coef_

(array([  32.14928032, -242.82449076,  559.98996952,  407.63766881,
        -718.69857577,  396.63703933,   10.432395  ,  171.81955335,
         627.07993787,  -21.62312454]),
 array([  0.        ,  -0.        , 425.89571524,  69.18564617,
          0.        ,   0.        ,  -0.        ,   0.        ,
        177.77602164,   0.        ]),
 array([  40.22980953,  -61.68895989,  273.28957886,  197.33039238,
          -1.61646667,  -19.12539101, -142.98112377,  107.37594422,
         195.22479197,   84.33273189]))

In [101]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=0).fit(X_train, y_train)
print(dt.score(X_test,y_test))

-0.15118398306085012


## Model evaluation

- cross validation: Breaks data into 10 parts and trains the models on 9 of the partitions and tests the score on one of the partitons that the model is not rained on
- Mean Absolute Error (MAE)
- For certain loss functions, the lower the value: more accurate the model. And for others, higher value: more accurate 
    - Coefficient of Determination: means how well the model fits the data, 0.6 means the model fits 60% of the data
    - MAE: the lower this value, the more accurate the results

In [117]:
from sklearn.model_selection import cross_val_score

print(cross_val_score(reg, df.iloc[:,:-1], df.target, cv=10))
print(cross_val_score(dt, df.iloc[:,:-1], df.target, cv=10))


[0.5561455  0.23055827 0.35357673 0.62190752 0.2658727  0.61819798
 0.41815142 0.43513747 0.43436229 0.68569253]
[-0.39292219 -0.46749346  0.02768473  0.06441362 -0.50323135  0.16437202
  0.11242982 -0.73798979 -0.30953155 -0.00137327]


In [119]:
from sklearn.metrics import mean_squared_error

reg_mae = mean_squared_error(reg.predict(X_test), y_test)
lasso_mae = mean_squared_error(lasso.predict(X_test), y_test)
ridge_mae = mean_squared_error(ridge.predict(X_test), y_test)
dt_mae = mean_squared_error(dt.predict(X_test), y_test)

print(reg_mae, lasso_mae, ridge_mae, dt_mae)